### ISSUE TITLE
Readme.md - Markdown Language

### ISSUE THREAD

**Issue by Rachit1313** [sshah135/Converter#2]
Hi,

You are supposed to use Markdown language for readme.md and not html.
Kindly use the markdown tags.

Example:
instead of h1 use #
instead of h2 use ##
instead of h3 use ###

For <br> you need to leave a line between the two lines.

Kindly refer to the guide provided in #1 

Thank you

**Comment by sshah135** [comment]
HI, 

Thank you for your help, I have updated my file with Markdown language 

with the example that you provided.

Thank you !
