### ISSUE TITLE
Regarding updating the "How to run part in README.md" file

### ISSUE THREAD

**Issue by bhavik001** [sshah135/Converter#3]
Hi,
I think you have do so many editing in README.md file in the How to run part.
You also have to update the 
```bash 
git clone https://github.com/yourusername/text-to-html-converter.git
```
 command to
 ```bash 
git clone https://github.com/sshah135/Converter.git
```
Then do:
```bash 
cd Converter
```
![image](https://github.com/sshah135/Converter/assets/95668553/9e0202c4-f112-4fb8-b7ed-5077816213f9)

**Comment by sshah135** [comment]
It's updated now !
