### ISSUE TITLE
The command for running the server is not working properly

### ISSUE THREAD

**Issue by bhavik001** [sshah135/Converter#5]
Hello!
Please update the command for running the server:
![image](https://github.com/sshah135/Converter/assets/95668553/cbbbc043-7cdb-48a6-b5d1-aa09334da8d0)

**Comment by sshah135** [comment]
Hi Bhavik, Thank you for your response but for this you need to run the command javac testtohtmlconverter to compile it first and then run it. I will add that into my readme
