### ISSUE TITLE
Request for Improved Documentation on Running the Code Locally

### ISSUE THREAD

**Issue by bhavik001** [sshah135/Converter#6]
Hello,
Firstly, I want to express my appreciation for the effort you've put into developing and maintaining this repository. I made an effort to execute the code from your repository locally, but I ran into some difficulties. Unfortunately, the available instructions didn't offer enough direction for a flawless setup, and I eventually didn't get the outcomes I was hoping for.
I respectfully ask that you take into consideration provide more thorough details or a step-by-step tutorial on how to execute the code locally. This would be of tremendous help to me as well as other potential users who could run into similar issues.

**Comment by sshah135** [comment]
Thank you bhavik, As for readme, I have updated it fully you can try now and let me know if that works for you.
